services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    command: ["./wait-for-it.sh"]
  db:
    image: postgres
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test_url_shortener
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432

volumes:
  postgresdb:
