services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    networks:
      - django-network
    depends_on:
      - db
    command: ["./wait-for-it.sh"]
    volumes:
      - static_volume:/code/staticfiles
  db:
    image: postgres
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test_url_shortener
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432
    networks:
      - django-network
  nginx:
    build: ../nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - django-network
networks:
  django-network:
    name: django-network
volumes:
  postgresdb:
  static_volume:
